-- ═══════════════════════════════════════════════════════════════
--  LEGADO — NÃO USAR EM PRODUÇÃO
-- ═══════════════════════════════════════════════════════════════
--
--  Esta migration está OBSOLETA e foi movida para:
--       legacy/001_initial.sql
--
--  Motivo:
--       Cria schemas incorretos que divergem do schema oficial
--       definido em data/db.py + migrations posteriores.
--
--  Consequências conhecidas:
--       - Coluna fantasma "nome" em adicional_categoria
--       - PK errada (id) em adicional_categoria e configuracoes
--       - Colunas faltando (restaurante_id, status, etc.)
--       - Defaults errados (status 'pendente' em vez de 'novo')
--       - Faltam colunas essenciais (itens, taxa_entrega, etc.)
--
--  Use exclusivamente init_db() → _run_migrations().
--
-- ═══════════════════════════════════════════════════════════════

SELECT 1 FROM information_schema.tables LIMIT 0;
-- Migration vazia: arquivo mantido apenas para não quebrar
-- o registro de schema_migrations em bancos existentes.
